balh: add aliyun upos
ipcjs/bilibili-helper pull request #1047
Opened 2022-08-28 13:19 UTC by arimitx

Add new upos server provided by aliyun

2022-08-29 16:34 UTC, ipcjs requested changes
另外这里带版本号也要加一下：https://github.com/ipcjs/bilibili-helper/blob/user.js/packages/unblock-area-limit/src/main.user.js#L4

2022-08-29 16:34 UTC, ipcjs commented on packages/unblock-area-limit/src/util/converters.ts
> +    alib: 'upos-sz-mirroralib.bilivideo.com',
这个`alib`不让选？

2022-08-29 17:24 UTC, arimitx commented on packages/unblock-area-limit/src/util/converters.ts
> +    alib: 'upos-sz-mirroralib.bilivideo.com',
版本号由您来决定吧。

alib是参考其他cdn加的一个备选项，但是替换upos那里似乎只能选主选项（比如金山只会选ks3而不能选ks3b, ks3c这种）？如果想在同一个CDN provider里做fallback，替换upos的函数似乎要重写（太懒了暂时只把ali加进去了，逃

2022-08-30 17:27 UTC, ipcjs commented on packages/unblock-area-limit/src/util/converters.ts
> +    alib: 'upos-sz-mirroralib.bilivideo.com',
哦, 原来以前也有a/b/c, 这部分是copy的别人的, 都没注意😅

2022-08-30 17:29 UTC, ipcjs commented on packages/unblock-area-limit/src/util/converters.ts
> +    alib: 'upos-sz-mirroralib.bilivideo.com',
现在是用action自动构建，改完版本号，我就只需要点merge了🫠

2022-08-30 17:30 UTC, merged